Change Trainer.setEggs() to put best eggs in all available incubators.
rubenvereecken/pokemongo-api pull request #94
Opened 2016-08-12 19:29 UTC by jmaygarden

The current code tries to put the first egg in the list in the first incubator in the list without regard to (a) the egg already being in an incubator or (b) the incubator already containing an egg. Additionally, the current code will only place a single egg in a single incubator in the best case. This change utilizes all empty incubators and prioritizes eggs that are not already in an incubator based on distance (i.e. 10km > 5km >2km).

2016-08-13 10:46 UTC, dnsBlah commented
i rather sort the eggs in timestamp
and incubate in order i gathered then

2016-08-13 12:04 UTC, jmaygarden commented
That could be done as well. Is there an advantage to either method?

2016-08-13 15:20 UTC, dnsBlah commented
no? 😆 i just like to have the bot play as i play
always wanna get rid of the eggs when i get then

2016-08-13 15:42 UTC, jmaygarden commented
How about I change it to take a sort key as a parameter and default to not sorting?

2016-08-13 17:40 UTC, dnsBlah commented
why you need a sort key then
just follow the order which comes from your inventory

2016-08-15 18:47 UTC, merged

2024-07-22 15:49 UTC, Limbersky23 approved these changes

2024-07-22 15:50 UTC, Limbersky23 requested changes
Uu

2024-07-22 15:51 UTC, Limbersky23 approved these changes

2024-07-22 15:52 UTC, Limbersky23 approved these changes

2024-07-22 15:53 UTC, Limbersky23 requested changes
Xx

2024-07-22 15:54 UTC, Limbersky23 requested changes
Xy